config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :courses, only: [:show, :index]
  resources :users, only: [:show, :index]
  resources :usercourses
  get 'add_teachers', to: 'courses#add_teacher'
  get 'add_courses', to: 'users#add_course'
  get 'search_courses', to: 'users#search'
  delete 'removeTakeCourse', to: 'users#removetake'
  post 'add_takecourse', to: 'users#add_takecourse'
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/views/usercourse/_lookup.html.erb
<div class="class" style="margin-bottom: 20px;">
  <h3 align="center">add new course</h3>
  <%= form_tag search_courses_path, remote: true, method: :get, id: "course-search-form" do %>
    <div class="input-group col-md-12">
      <%= text_field_tag :search_param, params[:search_param], placeholder: "Course Info", autofocus: true, class: "form-control py-2" %>
      <span class="input-group-append">
        <%= button_tag(type: :submit, class: "btn btn-outline-secondary") do %>
          <i class="fa fa-search"></i>
        <% end %>
        <!-- <button class="btn btn-outline-secondary" type="button">
            <i class="fa fa-search"></i>
        </button> -->
      </span>
          <!-- <input class="form-control py-2" type="search" id="example-search-input"> -->
    </div>
  <% end %>
</div>
<div id="results">
  <%= render 'usercourse/result' %>
</div>

app/views/usercourse/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= render 'layouts/messages' %>
  </div>
<% end %>

<% if @courses %>
 <% if @courses.size > 0 %>
    <div id="friend-lookup-results" class="well results-block col-md-10">
      <table class="table table-strip col-md-12">
        <thead>
          <tr>
            <th scope="col"><strong>Course Number</strong></th>
            <th scope="col"><strong>Course Name</strong></th>
            <th scope="col"><strong>Section</strong></th>
            <th scope="col"><strong>Action</strong></th>
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td><%= course.course_number %></td>
              <td><%= course.title %></td>
              <td><%= course.section %></td>
              <td><%= link_to "View Details", course_path(course), class: "btn btn-sm btn-success" %>
                <% if !current_user.has_take_course?(course.id) %>
                  <%= link_to "Add Course", add_takecourse_path(user: current_user, course: course, relationtype: "take"),
                                                  class: "btn btn-sm btn-success", method: :post %>
                <% else %>
                  <span class="label label-primary">
                    You have aready taken this course!
                  </span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/usercourse/_result.js.erb
$('#results').html("<%= j (render 'usercourse/result.html') %>")