config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :courses, only: [:show, :index]
  resources :users, only: [:show, :index]
  resources :usercourses
  get 'add_teachers', to: 'courses#add_teacher'
  get 'add_courses', to: 'users#add_course'
  get 'search_courses', to: 'users#search'
  delete 'removeTakeCourse', to: 'users#removetake'
  post 'add_takecourse', to: 'users#add_takecourse'
end

app/views/teachers/_adding.html.erb
<div class="card text-center">
  <%= form_tag add_teachers_path, method: :get do %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
            </tr>
          </thead>
          <tbody>
            <% @reorder_users.each do |t| %>
              <% if !t.admin? %>
                <tr>
                  <td><%= check_box_tag "user#{t.id}", 'yes', @teacher_ids.include?(t.id) ? true : false, disabled: @conflict_users.include?(t.id) ? true : false %></td>
                  <td><h3><%= content_tag( :span, "#{t.first_name} #{t.last_name}", :class=>'badge badge-light') %></h3></td>
                  <td><h3><%= content_tag( :span, "#{t.email}", :class=>'badge badge-light badge_class') %></h3></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
          </table>

          <%= hidden_field_tag 'token', "#{@course.id}" %>
          <%= button_tag(type: :submit, class: "btn btn-sm btn-success submit-class") do %>
            submit
          <% end %>
    <% end %>
</div>

app/views/teachers/_result.html.erb
<div class="card">
  <div class="card-header">
    <h3>Teacher Assistants for this course</h3>
  </div>
  <div class="card-body">
    <table class="table table-sm table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @teachers.each do |teacher| %>
          <tr>
            <td><%= teacher.last_name %> <%=teacher.first_name %></td>
            <td><%= teacher.email %></td>
            <td>
              <%= link_to "Remove", usercourses_path(teacher), method: :delete,
                data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/teachers/_result.js.erb
$('#results').html("<%= j (render 'teachers/result.html') %>")