config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :courses, only: [:show, :index]
  resources :users, only: [:show, :index]
  resources :usercourses
  get 'add_teachers', to: 'courses#add_teacher'
  get 'add_courses', to: 'users#add_course'
  get 'search_courses', to: 'users#search'
  delete 'removeTakeCourse', to: 'users#removetake'
  post 'add_takecourse', to: 'users#add_takecourse'
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
    Copyright © 2019
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container alert-message">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %> alert-dismissible fade show' role="alert">
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm   navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <% if current_user.admin? %>
                  <%= link_to 'Students', users_path, class: "nav-link" %>
                <% else %>
                  <%= link_to 'Search Course', add_courses_path, class: "nav-link" %>
                <% end %>
              </li>
              <!-- <li class="nav-item dropdown dmenu">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Actions
              </a>
              <div class="dropdown-menu sm-menu">
                <a class="dropdown-item" href="#">service 2</a>
                <a class="dropdown-item" href="#">service 3</a>
              </div>
            </li> -->
            <li class="nav-item">
              <%= link_to 'Course List', courses_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'My Schedule', user_path(current_user), class: "nav-link" %>
            </li>
             <!-- <li class="nav-item dropdown dmenu">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Dropdown link
              </a>
              <div class="dropdown-menu sm-menu">
                <a class="dropdown-item" href="#">Link 1</a>
                <a class="dropdown-item" href="#">Link 2</a>
                <a class="dropdown-item" href="#">Link 3</a>
                <a class="dropdown-item" href="#">Link 4</a>
                <a class="dropdown-item" href="#">Link 5</a>
                <a class="dropdown-item" href="#">Link 6</a>
              </div>
          </li> -->
          <% end %>
          </ul>
          <div class="social-part">

            <% if logged_in? %>
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                  <% if current_user.admin? %>
                    <%= link_to '<i class="fa fa-user-circle" aria-hidden="true"> Your Profile (Admin)</i>'.html_safe, user_path(current_user), class: "nav-link" %>
                  <% else %>
                    <%= link_to '<i class="fa fa-user-circle" aria-hidden="true"> Your Profile</i>'.html_safe, user_path(current_user), class: "nav-link" %>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
                </li>
              </ul>
            <% else %>
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                  <%= link_to 'Sign In', login_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherAssistantSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>